# Each language can have one grammar, it needs a name (used for the directory), the git repository
# to clone, and optionally a commit to checkout a specific commit of the grammar repository.
#
# For example, to add a language 'foo' we need to add something like:
#
#     foo = {
#         name="tree-sitter-foo",
#         git="git@github.com:pseudomata/tree-sitter-foo.git",
#         version="04937885edaae68e9b52001b88a6f72daeda391e"
#     }

[languages]
ada = { name="tree-sitter-ada", git="git@github.com:briot/tree-sitter-ada.git" }
agda = { name="tree-sitter-agda", git="git@github.com:tree-sitter/tree-sitter-agda.git" }
bash = { name="tree-sitter-bash", git="git@github.com:tree-sitter/tree-sitter-bash.git" }
c = { name="tree-sitter-c", git="git@github.com:tree-sitter/tree-sitter-c.git" }
c-sharp = { name="tree-sitter-c-sharp", git="git@github.com:tree-sitter/tree-sitter-c-sharp.git" }
capnp = { name="tree-sitter-capnp", git="git@github.com:amaanq/tree-sitter-capnp.git" }
clojure = { name="tree-sitter-clojure", git="git@github.com:sogaiu/tree-sitter-clojure.git" }
commonlisp = { name="tree-sitter-commonlisp", git="git@github.com:theHamsta/tree-sitter-commonlisp.git" }
cpp = { name="tree-sitter-cpp", git="git@github.com:tree-sitter/tree-sitter-cpp.git" }
css = { name="tree-sitter-css", git="git@github.com:tree-sitter/tree-sitter-css.git" }
d = { name="tree-sitter-d", git="git@github.com:gdamore/tree-sitter-d.git" }
dockerfile = { name="tree-sitter-dockerfile", git="git@github.com:camdencheek/tree-sitter-dockerfile.git" }
elisp = { name="tree-sitter-elisp", git="git@github.com:Wilfred/tree-sitter-elisp.git" }
elixir = { name="tree-sitter-elixir", git="git@github.com:elixir-lang/tree-sitter-elixir.git" }
elm = { name="tree-sitter-elm", git="git@github.com:elm-tooling/tree-sitter-elm.git" }
erlang = { name="tree-sitter-erlang", git="git@github.com:WhatsApp/tree-sitter-erlang.git" }
gleam = { name="tree-sitter-gleam", git="git@github.com:gleam-lang/tree-sitter-gleam.git" }
go = { name="tree-sitter-go", git="git@github.com:tree-sitter/tree-sitter-go.git" }
hack = { name="tree-sitter-hack", git="git@github.com:slackhq/tree-sitter-hack.git" }
haskell = { name="tree-sitter-haskell", git="git@github.com:tree-sitter/tree-sitter-haskell.git" }
html = { name="tree-sitter-html", git="git@github.com:tree-sitter/tree-sitter-html.git" }
java = { name="tree-sitter-java", git="git@github.com:tree-sitter/tree-sitter-java.git" }
javascript = { name="tree-sitter-javascript", git="git@github.com:tree-sitter/tree-sitter-javascript.git" }
jsdoc = { name="tree-sitter-jsdoc", git="git@github.com:tree-sitter/tree-sitter-jsdoc.git" }
json = { name="tree-sitter-json", git="git@github.com:tree-sitter/tree-sitter-json.git" }
julia = { name="tree-sitter-julia", git="git@github.com:tree-sitter/tree-sitter-julia.git" }
kotlin = { name="tree-sitter-kotlin", git="git@github.com:fwcd/tree-sitter-kotlin.git" }
latex = { name="tree-sitter-latex", git="git@github.com:latex-lsp/tree-sitter-latex.git" }
llvm = { name="tree-sitter-llvm", git="git@github.com:benwilliamgraham/tree-sitter-llvm.git" }
lua = { name="tree-sitter-lua", git="git@github.com:tjdevries/tree-sitter-lua.git" }
markdown = { name="tree-sitter-markdown", git="git@github.com:MDeiml/tree-sitter-markdown.git" }
nix = { name="tree-sitter-nix", git="git@github.com:nix-community/tree-sitter-nix.git" }
objc = { name="tree-sitter-objc", git="git@github.com:jiyee/tree-sitter-objc.git" }
ocaml = { name="tree-sitter-ocaml", git="git@github.com:tree-sitter/tree-sitter-ocaml.git" }
org = { name="tree-sitter-org", git="git@github.com:milisims/tree-sitter-org.git" }
pascal = { name="tree-sitter-pascal", git="git@github.com:Isopod/tree-sitter-pascal.git" }
perl = { name="tree-sitter-perl", git="https://github.com/tree-sitter-perl/tree-sitter-perl" }
php = { name="tree-sitter-php", git="git@github.com:tree-sitter/tree-sitter-php.git" }
protobuf = { name="tree-sitter-protobuf", git="git@github.com:mitchellh/tree-sitter-proto.git" }
python = { name="tree-sitter-python", git="git@github.com:tree-sitter/tree-sitter-python.git" }
ql = { name="tree-sitter-ql", git="git@github.com:tree-sitter/tree-sitter-ql.git" }
r = { name="tree-sitter-r", git="git@github.com:r-lib/tree-sitter-r.git" }
racket = { name="tree-sitter-racket", git="git@github.com:6cdh/tree-sitter-racket.git "}
regex = { name="tree-sitter-regex", git="git@github.com:tree-sitter/tree-sitter-regex.git" }
ruby = { name="tree-sitter-ruby", git="git@github.com:tree-sitter/tree-sitter-ruby.git" }
rust = { name="tree-sitter-rust", git="git@github.com:tree-sitter/tree-sitter-rust.git" }
scala = { name="tree-sitter-scala", git="git@github.com:tree-sitter/tree-sitter-scala.git" }
scheme = { name="tree-sitter-scheme", git="git@github.com:6cdh/tree-sitter-scheme.git" }
sml = { name="tree-sitter-sml", git="git@github.com:MatthewFluet/tree-sitter-sml.git" }
swift = { name="tree-sitter-swift", git="git@github.com:alex-pinkus/tree-sitter-swift.git" }
toml = { name="tree-sitter-toml", git="git@github.com:ikatyang/tree-sitter-toml.git" }
typescript = { name="tree-sitter-typescript", git="git@github.com:tree-sitter/tree-sitter-typescript.git" }
verilog = { name="tree-sitter-verilog", git="git@github.com:tree-sitter/tree-sitter-verilog.git" }
