# Each language can have one grammar, it needs a name (used for the directory), the git repository
# to clone, and optionally a commit to checkout a specific commit of the grammar repository.
#
# For example, to add a language 'foo' we need to add something like:
#
#     foo = {
#         name="tree-sitter-foo",
#         git="git@github.com:pseudomata/tree-sitter-foo.git",
#         version="04937885edaae68e9b52001b88a6f72daeda391e"
#     }

[languages]
agda = { name="tree-sitter-agda", git="git@github.com:tree-sitter/tree-sitter-agda.git" }
bash = { name="tree-sitter-bash", git="git@github.com:tree-sitter/tree-sitter-bash.git" }
c = { name="tree-sitter-c", git="git@github.com:tree-sitter/tree-sitter-c.git" }
c-sharp = { name="tree-sitter-c-sharp", git="git@github.com:tree-sitter/tree-sitter-c-sharp.git" }
cpp = { name="tree-sitter-cpp", git="git@github.com:tree-sitter/tree-sitter-cpp.git" }
css = { name="tree-sitter-css", git="git@github.com:tree-sitter/tree-sitter-css.git" }
go = { name="tree-sitter-go", git="git@github.com:tree-sitter/tree-sitter-go.git" }
haskell = { name="tree-sitter-haskell", git="git@github.com:tree-sitter/tree-sitter-haskell.git" }
html = { name="tree-sitter-html", git="git@github.com:tree-sitter/tree-sitter-html.git" }
java = { name="tree-sitter-java", git="git@github.com:tree-sitter/tree-sitter-java.git" }
javascript = { name="tree-sitter-javascript", git="git@github.com:tree-sitter/tree-sitter-javascript.git" }
jsdoc = { name="tree-sitter-jsdoc", git="git@github.com:tree-sitter/tree-sitter-jsdoc.git" }
json = { name="tree-sitter-json", git="git@github.com:tree-sitter/tree-sitter-json.git" }
julia = { name="tree-sitter-julia", git="git@github.com:tree-sitter/tree-sitter-julia.git" }
ocaml = { name="tree-sitter-ocaml", git="git@github.com:tree-sitter/tree-sitter-ocaml.git" }
php = { name="tree-sitter-php", git="git@github.com:tree-sitter/tree-sitter-php.git" }
python = { name="tree-sitter-python", git="git@github.com:tree-sitter/tree-sitter-python.git" }
ql = { name="tree-sitter-ql", git="git@github.com:tree-sitter/tree-sitter-ql.git" }
regex = { name="tree-sitter-regex", git="git@github.com:tree-sitter/tree-sitter-regex.git" }
ruby = { name="tree-sitter-ruby", git="git@github.com:tree-sitter/tree-sitter-ruby.git" }
rust = { name="tree-sitter-rust", git="git@github.com:tree-sitter/tree-sitter-rust.git" }
scala = { name="tree-sitter-scala", git="git@github.com:tree-sitter/tree-sitter-scala.git" }
verilog = { name="tree-sitter-verilog", git="git@github.com:tree-sitter/tree-sitter-verilog.git" }
