name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  build-node:
    name: build-node
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Display Node versions
        run: |
          node --version
          npm --version

      - name: Install dependencies
        run: npm install

      - name: Cache examples
        uses: actions/cache@v4
        with:
          path: examples
          key: ${{ hashFiles('script/parse-examples') }}

      - name: Test corpus & parse examples
        run: npm test

  build-rust:
    name: build-rust
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Build
        run: cargo build --release

      - name: Test
        run: cargo test

  build-swift:
    name: build-swift
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: swift build

      - name: Test
        run: swift test
